"""PDF report renderer for Retina analysis runs.

Assembles an AnalysisRun into a branded HTML document, then converts
to PDF via WeasyPrint. Uses Jinja2 for template rendering and inline
SVG charts generated by the charts module.

Phase 1: Global styles, page shell, score ring, segmented donut.
"""

from __future__ import annotations

import base64
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, BaseLoader


def _ensure_weasyprint_libs() -> None:
    """Ensure native libraries are discoverable for WeasyPrint.

    On macOS, setting DYLD_LIBRARY_PATH at runtime has no effect because
    the dynamic linker reads it only at process startup (SIP restriction).
    Instead, we pre-load the required shared libraries by full path using
    ctypes so they're already resident when WeasyPrint/cairocffi need them.

    On Linux (Railway/nixpacks), we set LD_LIBRARY_PATH which does work
    at runtime for subsequent dlopen() calls.

    Safe to call multiple times — short-circuits via a module-level flag.
    """
    import ctypes
    import platform

    if getattr(_ensure_weasyprint_libs, "_done", False):
        return
    _ensure_weasyprint_libs._done = True

    if platform.system() == "Darwin":
        brew_lib = Path("/opt/homebrew/lib")
        if not brew_lib.exists():
            brew_lib = Path("/usr/local/lib")
        if not brew_lib.exists():
            return
        # Pre-load native libs by full path so ctypes.util.find_library()
        # and cffi's ffi.dlopen() can resolve them.
        for lib_name in [
            "libglib-2.0.dylib",
            "libgobject-2.0.dylib",
            "libpango-1.0.dylib",
            "libpangocairo-1.0.dylib",
            "libpangoft2-1.0.dylib",
            "libcairo.dylib",
            "libgdk_pixbuf-2.0.dylib",
            "libffi.dylib",
        ]:
            lib_path = brew_lib / lib_name
            if lib_path.exists():
                try:
                    ctypes.cdll.LoadLibrary(str(lib_path))
                except OSError:
                    pass
        os.environ["DYLD_LIBRARY_PATH"] = str(brew_lib)
    else:
        # Linux — set LD_LIBRARY_PATH if not already configured
        if not os.environ.get("LD_LIBRARY_PATH"):
            import glob as glob_mod
            nix_libs = glob_mod.glob("/nix/store/*/lib")
            if nix_libs:
                os.environ["LD_LIBRARY_PATH"] = ":".join(nix_libs)


# Best-effort at import time (works for main thread / CLI usage)
_ensure_weasyprint_libs()

from retina.models.normalized import AnalysisRun, SiteReport, StrategicQuadrant
from retina.report.charts import (
    LENS_ORDER,
    LENS_LABELS_SHORT,
    LENS_COLORS,
    QUADRANT_COLORS,
    Q_NO_BRAINER,
    Q_GROWTH,
    Q_QUICK_WIN,
    Q_TRANSFORM,
    grouped_bar_chart,
    horizontal_bar_chart,
    quadrant_matrix,
    score_ring,
    segmented_donut,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

LENS_NAMES_FULL = {
    "performance_technical_health": "Performance & Platform",
    "seo_ai_visibility": "SEO & AI Visibility",
    "brand_messaging": "Brand & Messaging",
    "experience_design": "Experience & Design",
    "conversion_strategy": "Conversion & Strategy",
}

LENS_SUBTITLES = {
    "performance_technical_health": "Speed, stability, and technical foundations of the site",
    "seo_ai_visibility": "How discoverable the website is to search engines, LLMs, and AI-driven discovery",
    "brand_messaging": "How clearly the website communicates who it is for, what it offers, and why it matters",
    "experience_design": "How intuitive, modern, and intentional the website feels across every touchpoint",
    "conversion_strategy": "How effectively the website turns attention into action and builds trust",
}

LENS_DESCRIPTIONS = {
    "performance_technical_health": (
        "How fast, stable, and well-built the website is under the hood \u2014 "
        "page speed, code quality, security, and core web vitals."
    ),
    "seo_ai_visibility": (
        "How discoverable the website is to search engines, LLMs, and the "
        "algorithms that increasingly determine who gets found first."
    ),
    "brand_messaging": (
        "How clearly the website communicates who it is for, what it offers, "
        "and why it matters."
    ),
    "experience_design": (
        "How intuitive, modern, and intentional the website feels \u2014 from "
        "navigation and layout to visual hierarchy and mobile responsiveness."
    ),
    "conversion_strategy": (
        "How effectively the website turns attention into action through clear "
        "CTAs, logical user paths, and trust-building content."
    ),
}

QUADRANT_LABELS = {
    "no_brainer": "No-Brainers",
    "growth_move": "Growth Moves",
    "quick_win": "Quick Wins",
    "transformational": "Transformational",
}

QUADRANT_PRIORITY = ["no_brainer", "quick_win", "growth_move", "transformational"]

# Sub-dimension display names
SUBDIM_DISPLAY_NAMES = {
    # Performance & Platform
    "speed_performance": "Speed & Performance",
    "code_quality": "Code Quality",
    "security_ssl": "Security & SSL",
    "core_web_vitals": "Core Web Vitals",
    # SEO & AI Visibility
    "on_page_seo": "On-Page SEO",
    "technical_seo": "Technical SEO",
    "ai_visibility": "AI Visibility",
    "structured_data": "Structured Data",
    # Brand & Messaging
    "value_proposition": "Value Proposition",
    "brand_differentiation": "Brand Differentiation",
    "brand_voice_messaging": "Brand Voice & Messaging",
    "brand_visual_language": "Brand Visual Language",
    # Experience & Design
    "navigation_architecture": "Navigation & Information Architecture",
    "interface_design": "Visual Design & Hierarchy",
    "responsiveness": "Mobile Responsiveness",
    "content_taxonomy": "Interaction & Micro-interactions",
    # Conversion & Strategy
    "call_to_action_logic": "Call-to-Action Clarity",
    "funnel_design": "User Flow & Pathing",
    "trust_signals": "Trust Signals & Social Proof",
    "lead_capture_form_design": "Content Strategy & Lead Capture",
}

# Lens badge display names (short, uppercase for recommendation pills)
LENS_BADGE_NAMES = {
    "performance_technical_health": "PLATFORM",
    "seo_ai_visibility": "SEO",
    "brand_messaging": "BRAND",
    "experience_design": "EXPERIENCE",
    "conversion_strategy": "CONVERSION",
}

ROADMAP_QUADRANT_COLORS = {
    "no_brainer": "#00C864",
    "quick_win": "#FFC800",
    "growth_move": "#4da6ff",
    "transformational": "#FF8C00",
}

# Category mapping for tech stack summary
TECH_CATEGORY_MAP = {
    "Hosted Solution": "CMS",
    "Headless": "CMS",
    "Enterprise": "CMS",
    "CMS": "CMS",
    "Audience Measurement": "Analytics",
    "Visitor Count Tracking": "Analytics",
    "Tag Management": "Analytics",
    "Analytics": "Analytics",
    "Feedback Forms and Surveys": "CRM",
    "Transactional Email": "CRM",
    "CRM": "CRM",
    "JavaScript Frameworks": "Framework",
    "Web Frameworks": "Framework",
    "Hosting": "Hosting",
    "Web Hosting": "Hosting",
    "DNS": "DNS",
    "CDN": "CDN",
    "Email": "Email",
    "Email Hosting": "Email",
    "Advertising": "Advertising",
    "JavaScript": "JavaScript",
    "Mobile": "Mobile",
}

TECH_NAME_OVERRIDES = {
    "Webflow": "CMS",
    "WordPress": "CMS",
    "Contentful": "CMS",
    "Shopify": "CMS",
    "Squarespace": "CMS",
    "HubSpot": "CRM",
    "Salesforce": "CRM",
    "Google Analytics": "Analytics",
    "Google Tag Manager": "Analytics",
    "Hotjar": "Analytics",
    "Segment": "Analytics",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _encode_image(source: str | Path | bytes, *, mime: str | None = None) -> str | None:
    """Encode an image as a base64 data URI for inline embedding.

    Accepts either a file path (str/Path) or raw bytes.
    Returns a ``data:<mime>;base64,...`` string, or None if the source
    is unavailable.

    Args:
        source: Local file path, or raw image bytes.
        mime: Explicit MIME type. Inferred from file extension when
              *source* is a path; defaults to ``image/png`` for bytes.
    """
    if isinstance(source, bytes):
        if not source:
            return None
        mime = mime or "image/png"
        b64 = base64.b64encode(source).decode("ascii")
        return f"data:{mime};base64,{b64}"

    # File-path branch
    p = Path(source)
    if not p.exists():
        logger.warning("Image not found: %s", p)
        return None
    if mime is None:
        suffix = p.suffix.lower()
        mime = {
            ".png": "image/png",
            ".jpg": "image/jpeg",
            ".jpeg": "image/jpeg",
            ".svg": "image/svg+xml",
            ".webp": "image/webp",
        }.get(suffix, "image/png")
    data = p.read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:{mime};base64,{b64}"


def fetch_screenshot_bytes(url: str) -> bytes | None:
    """Download a screenshot image from a URL and return raw bytes.

    Uses a synchronous HTTP client with a 15-second timeout.
    Returns None on any failure (network error, non-200 status, etc.).
    """
    try:
        import httpx
        with httpx.Client(follow_redirects=True) as client:
            response = client.get(url, timeout=15)
            if response.status_code == 200:
                return response.content
    except Exception as e:
        logger.warning("Screenshot fetch failed for %s: %s", url, e)
    return None


def _mime_from_url(url: str) -> str:
    """Guess MIME type from a URL's extension."""
    lower = url.lower().split("?")[0]
    if lower.endswith(".jpg") or lower.endswith(".jpeg"):
        return "image/jpeg"
    if lower.endswith(".webp"):
        return "image/webp"
    return "image/png"


def _read_svg(path: str | Path) -> str | None:
    """Read an SVG file and return its content, or None if missing."""
    p = Path(path)
    if not p.exists():
        return None
    return p.read_text(encoding="utf-8")


def _get_lens_scores(report: SiteReport) -> dict[str, float | None]:
    """Extract a dict of lens_key -> score from a SiteReport."""
    scores: dict[str, float | None] = {}
    scored_keys = set()
    for ls in report.retina_score.lens_scores:
        scores[ls.lens.value] = ls.score
        scored_keys.add(ls.lens.value)
    for key in LENS_ORDER:
        if key not in scored_keys:
            scores[key] = None
    return scores


def _has_analyst_scores(report: SiteReport) -> bool:
    """Check if a report has any analyst-scored lenses."""
    return any(not ls.is_automated for ls in report.retina_score.lens_scores)


def _get_max_score(report: SiteReport) -> float:
    """Determine max possible score based on which lenses are present."""
    return 100.0 if _has_analyst_scores(report) else 40.0


def _truncate(text: str, max_len: int = 200) -> str:
    """Truncate text to max_len, adding ellipsis if needed."""
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."


def _site_label(url: str) -> str:
    """Extract a readable label from a URL."""
    from urllib.parse import urlparse
    parsed = urlparse(url)
    return parsed.netloc or url


# ---------------------------------------------------------------------------
# Template — Global Styles + Page Shell
# ---------------------------------------------------------------------------

REPORT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
/* ================================================================
   Retina PDF Report — Global Foundation (Phase 1)
   ================================================================ */

@page {
    size: Letter;
    margin: 1in;
}

@page :first {
    margin: 0;
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

html, body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', sans-serif;
    font-size: 10.5px;
    line-height: 1.6;
    color: #1A1A2E;
    background: #FFFFFF;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
}

/* ---- CSS Custom Properties — Lens Colors ---- */
:root {
    --color-performance: #0066FF;
    --color-seo: #00B8D9;
    --color-brand: #7B61FF;
    --color-experience: #FF6B6B;
    --color-conversion: #FF8C00;
    --color-navy: #0A0E27;
    --color-accent: #0066FF;
    --color-gray-100: #F7F8FA;
    --color-gray-200: #E8E8E8;
    --color-gray-300: #D1D5DB;
    --color-gray-400: #9CA3AF;
    --color-gray-500: #6B7280;
    --color-gray-700: #374151;
    --color-white: #FFFFFF;
}

/* ---- Page container ---- */
/* Non-cover pages: content flows within @page margins automatically.
   Do NOT set explicit width — WeasyPrint uses the @page content area. */
.page {
    page-break-after: always;
    position: relative;
    background: #FFFFFF;
    overflow: hidden;
}

.page:last-child {
    page-break-after: avoid;
}

/* ---- Page Footer via @page margin boxes ---- */
@page {
    @bottom-left {
        content: "MATIC DIGITAL";
        font-family: -apple-system, BlinkMacSystemFont, sans-serif;
        font-size: 8px;
        font-weight: 700;
        letter-spacing: 0.5px;
        color: #1A1A2E;
        vertical-align: middle;
    }
    @bottom-center {
        content: "Retina Digital Experience Report";
        font-family: -apple-system, BlinkMacSystemFont, sans-serif;
        font-size: 8px;
        color: #6B7280;
        vertical-align: middle;
    }
    @bottom-right {
        content: counter(page);
        font-family: -apple-system, BlinkMacSystemFont, sans-serif;
        font-size: 9px;
        color: #6B7280;
        vertical-align: middle;
    }
}

/* Cover page: zero margins, no footer */
.page-cover {
    page: cover-page;
}

@page cover-page {
    margin: 0;
    @bottom-left { content: none; }
    @bottom-center { content: none; }
    @bottom-right { content: none; }
}

/* ---- Typography System ---- */

/* Section label — small uppercase colored text */
.section-label {
    font-size: 13px;
    font-weight: 700;
    text-transform: none;
    letter-spacing: 0;
    margin-bottom: 8px;
}

/* Page title — large bold heading */
.page-title {
    font-size: 28px;
    font-weight: 800;
    letter-spacing: -0.5px;
    line-height: 1.15;
    color: #1A1A2E;
    margin-bottom: 4px;
}

/* Page subtitle — URL or descriptor below title */
.page-url {
    font-size: 14px;
    font-weight: 400;
    color: var(--color-gray-500);
    margin-bottom: 20px;
}

/* Body text */
.body-text {
    font-size: 11px;
    font-weight: 400;
    line-height: 1.7;
    color: #1A1A2E;
    margin-bottom: 14px;
}

.body-text-lg {
    font-size: 12px;
    line-height: 1.7;
    color: #1A1A2E;
    margin-bottom: 16px;
}

.body-text-sm {
    font-size: 10px;
    line-height: 1.6;
    color: var(--color-gray-500);
    margin-bottom: 10px;
}

/* Card heading */
.card-heading {
    font-size: 16px;
    font-weight: 700;
    color: #1A1A2E;
    margin-bottom: 12px;
}

.card-subheading {
    font-size: 13px;
    font-weight: 600;
    color: #1A1A2E;
    margin-bottom: 8px;
}

/* ---- Card Component ---- */
.card {
    background: var(--color-white);
    border: 1px solid var(--color-gray-200);
    border-radius: 8px;
    padding: 20px;
    margin-bottom: 16px;
}

.card-gray {
    background: var(--color-gray-100);
    border: 1px solid var(--color-gray-200);
    border-radius: 8px;
    padding: 20px;
    margin-bottom: 16px;
}

/* ---- Standard Lens Page Header ---- */
.lens-header {
    margin-bottom: 20px;
    position: relative;
}

.lens-header .section-label {
    margin-bottom: 8px;
}

.lens-header .page-title {
    margin-bottom: 4px;
}

.lens-header .page-url {
    margin-bottom: 0;
}

.lens-header-icon {
    position: absolute;
    top: 0;
    right: 0;
    width: 56px;
    height: 56px;
}

.lens-header-icon svg {
    width: 56px;
    height: 56px;
}

/* ---- Score Card (used on lens pages) ---- */
.score-card {
    display: flex;
    align-items: center;
    padding: 20px;
    background: var(--color-white);
    border: 1px solid var(--color-gray-200);
    border-radius: 8px;
    margin-bottom: 16px;
}

.score-card-ring {
    flex-shrink: 0;
    margin-right: 20px;
}

.score-card-info {
    flex: 1;
}

.score-card-info h3 {
    font-size: 18px;
    font-weight: 700;
    color: #1A1A2E;
    margin-bottom: 4px;
}

.score-card-info p {
    font-size: 11px;
    color: var(--color-gray-500);
    line-height: 1.5;
}

.score-card-screenshot {
    flex-shrink: 0;
    width: 160px;
    margin-left: 16px;
    border-radius: 8px;
    overflow: hidden;
    border: 1px solid var(--color-gray-200);
}

.score-card-screenshot img {
    width: 100%;
    height: auto;
    display: block;
}

/* Thin color divider below score card */
.score-card-divider {
    height: 2px;
    margin: 0 0 20px 0;
    border: none;
}

/* ---- Two-Column Layout ---- */
.two-col {
    display: flex;
    gap: 20px;
}

.two-col > .col-left {
    flex: 1;
}

.two-col > .col-right {
    flex: 1;
}

/* ---- 2x2 Grid ---- */
.grid-2x2 {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
}

/* ---- Technology Pill Tags ---- */
.tech-pill {
    display: inline-block;
    font-size: 10px;
    font-weight: 500;
    color: #1A1A2E;
    background: var(--color-gray-100);
    border: 1px solid var(--color-gray-200);
    border-radius: 4px;
    padding: 3px 8px;
    margin: 2px 4px 2px 0;
}

/* ---- Lens Color Pill Badge ---- */
.lens-badge {
    display: inline-block;
    font-size: 9px;
    font-weight: 600;
    color: var(--color-white);
    border-radius: 4px;
    padding: 2px 8px;
    margin-top: 4px;
}

/* ---- Status Dot (CWV) ---- */
.status-dot {
    display: inline-block;
    width: 10px;
    height: 10px;
    border-radius: 50%;
    margin-right: 6px;
    vertical-align: middle;
}

.status-good { background: #22C55E; }
.status-needs-improvement { background: #F59E0B; }
.status-poor { background: #EF4444; }

/* ---- Lighthouse Score Pills ---- */
.lighthouse-pill {
    display: inline-block;
    font-size: 11px;
    font-weight: 600;
    color: var(--color-white);
    border-radius: 20px;
    padding: 6px 14px;
    margin: 0 8px 8px 0;
}

.lighthouse-pill-red { background: #EF4444; }
.lighthouse-pill-amber { background: #F59E0B; }
.lighthouse-pill-green { background: #22C55E; }

/* ---- Tech Stack Table ---- */
.tech-stack-table {
    width: 100%;
    border-collapse: collapse;
}

.tech-stack-table tr {
    border-bottom: 1px solid var(--color-gray-200);
}

.tech-stack-table tr:last-child {
    border-bottom: none;
}

.tech-stack-table td {
    padding: 10px 0;
    vertical-align: top;
    font-size: 10.5px;
}

.tech-stack-table td:first-child {
    font-weight: 700;
    color: #1A1A2E;
    width: 100px;
    padding-right: 16px;
}

/* ---- Analyst Sub-Dimension Grid Cell ---- */
.subdim-cell {
    padding: 12px;
}

.subdim-cell-title {
    font-size: 12px;
    font-weight: 700;
    color: #1A1A2E;
    margin-bottom: 8px;
}

.subdim-cell-body {
    display: flex;
    align-items: flex-start;
    gap: 12px;
}

.subdim-cell-ring {
    flex-shrink: 0;
}

.subdim-cell-text {
    font-size: 10px;
    line-height: 1.6;
    color: var(--color-gray-700);
}

/* ---- Recommendation Matrix ---- */
.rec-quadrant {
    padding: 16px;
}

.rec-quadrant-title {
    font-size: 14px;
    font-weight: 700;
    color: #1A1A2E;
    margin-bottom: 2px;
}

.rec-quadrant-desc {
    font-size: 10px;
    color: var(--color-gray-500);
    margin-bottom: 12px;
}

.rec-item {
    font-size: 10.5px;
    line-height: 1.6;
    color: #1A1A2E;
    margin-bottom: 10px;
    padding-bottom: 10px;
    border-bottom: 1px solid var(--color-gray-200);
}

.rec-item:last-child {
    border-bottom: none;
    margin-bottom: 0;
    padding-bottom: 0;
}

/* ---- Cover Page ---- */
.cover {
    width: 8.5in;
    min-height: 11in;
    background: #0A0E27;
    color: #FFFFFF;
    padding: 0.8in;
    position: relative;
    display: flex;
    flex-direction: column;
    page-break-after: always;
    overflow: hidden;
}

.cover-logo {
    margin-bottom: 0.6in;
}

.cover-logo svg {
    height: 40px;
    width: auto;
}

.cover-badge {
    display: inline-block;
    background: var(--color-accent);
    color: #FFFFFF;
    font-size: 13px;
    font-weight: 600;
    padding: 8px 20px;
    border-radius: 24px;
    margin-bottom: 20px;
}

.cover-title {
    font-size: 48px;
    font-weight: 800;
    letter-spacing: -1px;
    line-height: 1.1;
    color: #FFFFFF;
    margin-bottom: 12px;
}

.cover-subtitle {
    font-size: 16px;
    font-weight: 400;
    color: rgba(255, 255, 255, 0.75);
    margin-bottom: 0.4in;
    line-height: 1.5;
}

/* Dot grid pattern */
.cover-dots {
    flex: 1;
    position: relative;
    margin: 0.2in 0;
    overflow: hidden;
}

.cover-bottom {
    margin-top: auto;
}

.cover-bottom-text {
    font-size: 12px;
    font-weight: 400;
    color: rgba(255, 255, 255, 0.7);
    line-height: 1.6;
    margin-bottom: 0.3in;
    max-width: 65%;
}

.cover-footer {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
}

.cover-date-label {
    font-size: 11px;
    color: rgba(255, 255, 255, 0.5);
    margin-bottom: 2px;
}

.cover-date {
    font-size: 13px;
    color: rgba(255, 255, 255, 0.8);
}

.cover-footer-logo svg {
    height: 32px;
    width: auto;
}

/* ---- About This Report Page ---- */
.about-heading {
    font-size: 26px;
    font-weight: 800;
    line-height: 1.25;
    letter-spacing: -0.3px;
    color: #1A1A2E;
    margin-bottom: 16px;
}

.about-body {
    font-size: 11.5px;
    line-height: 1.7;
    color: #1A1A2E;
    margin-bottom: 14px;
}

.about-body-bold {
    font-size: 10px;
    font-weight: 600;
    line-height: 1.7;
    color: #1A1A2E;
    margin-bottom: 16px;
}

/* Lens table */
.lens-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 16px;
}

.lens-table-header {
    display: flex;
    justify-content: space-between;
    padding: 8px 12px;
    font-size: 10px;
    color: var(--color-gray-500);
    border-bottom: 1px solid var(--color-gray-200);
}

.lens-table-row {
    display: flex;
    align-items: center;
    padding: 14px 12px;
    border-bottom: 1px solid var(--color-gray-200);
}

.lens-table-row:last-child {
    border-bottom: none;
}

.lens-table-icon {
    width: 44px;
    height: 44px;
    flex-shrink: 0;
    margin-right: 14px;
}

.lens-table-icon svg {
    width: 44px;
    height: 44px;
}

.lens-table-content {
    flex: 1;
}

.lens-table-name {
    font-size: 14px;
    font-weight: 700;
    color: #1A1A2E;
    margin-bottom: 2px;
}

.lens-table-desc {
    font-size: 10.5px;
    color: var(--color-gray-500);
    line-height: 1.5;
}

.lens-table-pts {
    font-size: 20px;
    font-weight: 700;
    color: var(--color-accent);
    flex-shrink: 0;
    margin-left: 12px;
    white-space: nowrap;
    text-align: right;
    min-width: 70px;
}

/* Understanding scores box */
.scores-explainer {
    background: var(--color-gray-100);
    border: 1px solid var(--color-gray-200);
    border-radius: 8px;
    padding: 16px 20px;
    display: flex;
    align-items: center;
}

.scores-explainer-text {
    flex: 1;
    margin-right: 20px;
}

.scores-explainer-text h4 {
    font-size: 12px;
    font-weight: 700;
    color: #1A1A2E;
    margin-bottom: 6px;
}

.scores-explainer-text p {
    font-size: 10px;
    line-height: 1.6;
    color: var(--color-gray-500);
}

.scores-explainer-total {
    font-size: 30px;
    font-weight: 700;
    color: var(--color-accent);
    flex-shrink: 0;
    white-space: nowrap;
    min-width: 90px;
    text-align: right;
}

/* ---- Performance Summary Page ---- */
.summary-header-right {
    position: absolute;
    top: 0;
    right: 0;
    text-align: right;
    font-size: 11px;
    color: var(--color-gray-500);
}

.summary-header-right .analyst-name {
    font-weight: 600;
    color: #1A1A2E;
}

/* ---- CWV Metric Card ---- */
.cwv-cell {
    padding: 12px 0;
}

.cwv-cell-header {
    display: flex;
    align-items: center;
    margin-bottom: 4px;
}

.cwv-cell-name {
    font-size: 11px;
    font-weight: 600;
    color: #1A1A2E;
}

.cwv-cell-value {
    font-size: 28px;
    font-weight: 700;
    color: #1A1A2E;
    margin-bottom: 4px;
}

.cwv-cell-comparison {
    font-size: 10px;
    color: var(--color-gray-500);
    margin-bottom: 8px;
}

.cwv-cell-comparison .warn {
    color: #EF4444;
    font-weight: 600;
}

.cwv-cell-interpretation {
    font-size: 10px;
    line-height: 1.6;
    color: var(--color-gray-700);
    margin-bottom: 8px;
}

.cwv-cell-benchmark {
    font-size: 9.5px;
    font-style: italic;
    color: var(--color-gray-500);
    line-height: 1.5;
}

/* ---- Utility ---- */
.text-center { text-align: center; }
.text-right { text-align: right; }
.mt-0 { margin-top: 0; }
.mt-4 { margin-top: 4px; }
.mt-8 { margin-top: 8px; }
.mt-16 { margin-top: 16px; }
.mb-0 { margin-bottom: 0; }
.mb-4 { margin-bottom: 4px; }
.mb-8 { margin-bottom: 8px; }
.mb-16 { margin-bottom: 16px; }
.mb-20 { margin-bottom: 20px; }

.color-performance { color: var(--color-performance); }
.color-seo { color: var(--color-seo); }
.color-brand { color: var(--color-brand); }
.color-experience { color: var(--color-experience); }
.color-conversion { color: var(--color-conversion); }

.bg-performance { background-color: var(--color-performance); }
.bg-seo { background-color: var(--color-seo); }
.bg-brand { background-color: var(--color-brand); }
.bg-experience { background-color: var(--color-experience); }
.bg-conversion { background-color: var(--color-conversion); }

/* Dot grid for cover — CSS generated */
.dot-grid {
    display: grid;
    grid-template-columns: repeat(20, 1fr);
    grid-template-rows: repeat(10, 1fr);
    gap: 6px;
    width: 100%;
    height: 100%;
}

.dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    justify-self: center;
    align-self: center;
}

</style>
</head>
<body>

<!-- ============================================================ -->
<!-- COVER PAGE                                                     -->
<!-- ============================================================ -->
<div class="cover page-cover">
    {% if retina_logo_svg %}
    <div class="cover-logo">{{ retina_logo_svg | safe_svg_white }}</div>
    {% else %}
    <div class="cover-logo" style="font-size: 24px; font-weight: 700; letter-spacing: -0.5px;">Matic Retina</div>
    {% endif %}

    <div class="cover-badge">Digital Experience Report</div>

    <h1 class="cover-title">{{ project_title }}</h1>
    <p class="cover-subtitle">An intelligent review on five pillars of digital readiness</p>

    <!-- Decorative dot grid -->
    <div class="cover-dots">
        <svg width="100%" height="100%" viewBox="0 0 600 300" xmlns="http://www.w3.org/2000/svg">
            {% for row in range(12) %}
            {% for col in range(20) %}
            {% set x = col * 32 + 8 %}
            {% set y = row * 26 + 8 %}
            {% set hash = (row * 20 + col) * 7 % 100 %}
            {% if hash < 70 %}
            <circle cx="{{ x }}" cy="{{ y }}" r="{{ [3, 4, 5, 6, 7][hash % 5] }}"
                    fill="{{ ['#0066FF', '#00B8D9', '#7B61FF', '#4A90D9', '#0044CC', '#00B8D9'][hash % 6] }}"
                    opacity="{{ [0.3, 0.5, 0.7, 0.9, 1.0][hash % 5] }}" />
            {% endif %}
            {% endfor %}
            {% endfor %}
        </svg>
    </div>

    <div class="cover-bottom">
        <p class="cover-bottom-text">
            We analyzed the website {{ primary_url }} to assess the SEO &amp; AI visibility,
            technical platform performance, and how effectively it converts, engages,
            and builds trust online.
        </p>

        <div class="cover-footer">
            <div>
                <div class="cover-date-label">Date Prepared</div>
                <div class="cover-date">{{ analysis_date }}</div>
            </div>
            {% if matic_logo_svg %}
            <div class="cover-footer-logo">{{ matic_logo_svg | safe_svg_white }}</div>
            {% endif %}
        </div>
    </div>
</div>

<!-- ============================================================ -->
<!-- ABOUT THIS REPORT                                              -->
<!-- ============================================================ -->
<div class="page">
    <div class="section-label color-performance">About this report</div>

    <h2 class="about-heading">
        Retina evaluates real-world digital experiences to reveal where online
        performance is being won or lost.
    </h2>

    <p class="about-body">
        Digital experience and AI visibility online are the primary drivers of awareness,
        consideration, and conversion. Gaps in clarity, usability, or performance create
        friction that costs pipeline, even for the strongest brands.
    </p>

    <p class="about-body-bold">
        Retina combines AI-powered analysis with expert strategic evaluation to surface
        exactly where those gaps are and what to do about them. Each website is assessed
        across five lenses on a 100-point scale. Two lenses are scored automatically using
        performance and technology data. Three are evaluated by a Matic strategist reviewing
        brand, experience, and conversion strategy. The result is a competitive intelligence
        report with prioritized recommendations mapped by effort and impact.
    </p>

    <!-- Lens Table -->
    <div class="card" style="padding: 0;">
        <div class="lens-table-header" style="padding: 10px 16px;">
            <span>Lens</span>
            <span>Max. value</span>
        </div>
        {% for lens_key in lens_order %}
        <div class="lens-table-row" style="padding: 12px 16px;">
            {% if lens_icons[lens_key] %}
            <div class="lens-table-icon">{{ lens_icons[lens_key] }}</div>
            {% endif %}
            <div class="lens-table-content">
                <div class="lens-table-name">{{ lens_names[lens_key] }}</div>
                <div class="lens-table-desc">{{ lens_descriptions[lens_key] }}</div>
            </div>
            <div class="lens-table-pts">20 pts</div>
        </div>
        {% endfor %}
    </div>

    <!-- Understanding Scores -->
    <div class="scores-explainer">
        <div class="scores-explainer-text">
            <h4>Understanding scores</h4>
            <p>
                Each of the five lenses is weighted equally at 20 points. A score of 15 or
                above signals competitive strength in that dimension; anything below highlights
                an opportunity. Together, the five lenses roll up into a composite 100-point
                Retina Score \u2014 a single measure of overall digital experience readiness
                relative to the competitive set.
            </p>
        </div>
        <div class="scores-explainer-total">100 pts</div>
    </div>
</div>

<!-- ============================================================ -->
<!-- PERFORMANCE SUMMARY                                            -->
<!-- ============================================================ -->
<div class="page">
    <div class="lens-header" style="position: relative;">
        <div class="section-label color-performance">Performance summary</div>
        <h2 class="page-title">{{ project_title }}</h2>
        <div class="page-url">{{ primary_url }}</div>
        {% if analyst_name or analysis_date %}
        <div class="summary-header-right">
            {% if analyst_name %}
            <div style="font-size: 11px; color: #6B7280;">Analyst</div>
            <div class="analyst-name">{{ analyst_name }}</div>
            {% endif %}
            <div style="margin-top: 4px;">{{ analysis_date }}</div>
        </div>
        {% endif %}
    </div>

    <!-- Score Rating Card -->
    <div class="card">
        <div class="card-heading mb-8">Score Rating</div>
        <div class="two-col">
            <div class="col-left" style="text-align: center;">
                {{ donut_chart_svg }}
            </div>
            <div class="col-right">
                {{ summary_bar_chart_svg }}
            </div>
        </div>
    </div>

    <!-- Technology Stack + Screenshot -->
    <div class="card">
        <div class="two-col">
            <div class="col-left">
                <div class="card-heading mb-8">Technology Stack</div>
                {% if tech_summary %}
                {% for cat_label, tech_names in tech_summary %}
                <div style="margin-bottom: 8px;">
                    <div style="font-size: 10px; font-weight: 700; text-transform: uppercase; color: #1A1A2E; margin-bottom: 4px;">{{ cat_label }}</div>
                    <div>
                        {% for name in tech_names.split(', ') %}
                        <span class="tech-pill">{{ name }}</span>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <p class="body-text-sm" style="font-style: italic;">Technology data not available.</p>
                {% endif %}
            </div>
            <div class="col-right">
                {% if screenshot_data_uri %}
                <img src="{{ screenshot_data_uri }}" alt="Site screenshot"
                     style="width: 100%; border-radius: 6px; border: 1px solid #E2E8F0;" />
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Summary -->
    <div class="card">
        <div class="card-heading mb-8">Summary</div>
        {% if executive_summary %}
            {% for paragraph in executive_summary_paragraphs %}
            <p class="body-text">{{ paragraph }}</p>
            {% endfor %}
        {% else %}
        <p class="body-text" style="color: #6B7280; font-style: italic;">
            Executive summary will be generated once all lens evaluations are complete.
        </p>
        {% endif %}
    </div>
</div>

<!-- ============================================================ -->
<!-- ANALYST LENS PAGES                                             -->
<!-- ============================================================ -->
{% for analyst_page in analyst_lens_pages %}
<div class="page">
    <!-- Standard Lens Header -->
    <div class="lens-header">
        <div class="section-label" style="color: {{ analyst_page.color }};">{{ analyst_page.name }}</div>
        <h2 class="page-title">{{ project_title }}</h2>
        <div class="page-url">{{ primary_url }}</div>
        {% if analyst_page.icon_svg %}
        <div class="lens-header-icon">{{ analyst_page.icon_svg }}</div>
        {% endif %}
    </div>

    <!-- Score Card -->
    <div class="score-card">
        <div class="score-card-ring">
            {{ analyst_page.score_ring_svg }}
        </div>
        <div class="score-card-info">
            <h3>{{ analyst_page.name }}</h3>
            <p>{{ analyst_page.subtitle }}</p>
        </div>
        {% if analyst_page.screenshot_uri %}
        <div class="score-card-screenshot">
            <img src="{{ analyst_page.screenshot_uri }}" alt="Screenshot" />
        </div>
        {% endif %}
    </div>

    <!-- Overall Observations -->
    {% if analyst_page.observations %}
    <div class="card" style="margin-top: 16px;">
        <div class="card-heading">Overall Observations</div>
        {% for paragraph in analyst_page.observation_paragraphs %}
        <p class="body-text">{{ paragraph }}</p>
        {% endfor %}
    </div>
    {% endif %}

    <!-- Sub Dimensions -->
    {% if analyst_page.subdimensions %}
    <div class="card" style="margin-top: 8px;">
        <div style="display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 16px;">
            <div class="card-heading" style="margin-bottom: 0;">Sub Dimensions</div>
            <div style="font-size: 9px; color: #6B7280; font-style: italic;">4–5: Best in class · 3–3.5: Solid · 1.5–2.5: Notable gaps · 0.5–1: Critical</div>
        </div>
        <div class="grid-2x2">
            {% for subdim in analyst_page.subdimensions %}
            <div class="subdim-cell">
                <div class="subdim-cell-title">{{ subdim.name }}</div>
                <div class="subdim-cell-body">
                    <div class="subdim-cell-ring">
                        {{ subdim.ring_svg }}
                    </div>
                    <div class="subdim-cell-text">
                        {% if subdim.observation %}
                        {{ subdim.observation }}
                        {% else %}
                        <span style="font-style: italic; color: #9CA3AF;">No observations recorded yet</span>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>
{% endfor %}

<!-- ============================================================ -->
<!-- RECOMMENDATIONS                                                -->
<!-- ============================================================ -->
{% if has_recommendations %}
<div class="page">
    <div class="lens-header">
        <div class="section-label color-performance">Recommendations</div>
        <h2 class="page-title">{{ project_title }}</h2>
        <div class="page-url">{{ primary_url }}</div>
    </div>

    <div class="grid-2x2">
        {% for quad in recommendation_quadrants %}
        <div class="card">
            <div class="rec-quadrant-title" style="margin-bottom: 14px;">{{ quad.label }}</div>
            {% for rec in quad.recs %}
            <div style="margin-bottom: 14px;">
                <div style="margin-bottom: 4px;">
                    <span style="font-size: 11px; font-weight: 700; color: #1A1A2E;">{{ rec.title }}</span>
                    {% if rec.lens_color %}
                    <span class="lens-badge" style="background: {{ rec.lens_color }}; margin-left: 6px; vertical-align: middle;">{{ rec.lens_name }}</span>
                    {% endif %}
                </div>
                {% if rec.description %}
                <div style="font-size: 10px; line-height: 1.6; color: #374151;">{{ rec.description }}</div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

</body>
</html>
"""


# ---------------------------------------------------------------------------
# Data preparation
# ---------------------------------------------------------------------------


def _build_scorecard(
    report: SiteReport,
    *,
    is_primary: bool,
    index: int,
) -> dict:
    """Build template context for a single site scorecard."""
    scores = _get_lens_scores(report)
    max_score = _get_max_score(report)
    has_analyst = _has_analyst_scores(report)
    label = _site_label(report.normalized_url)

    ss_uri = None
    if report.screenshots and report.screenshots.viewport:
        ss_uri = _encode_image(report.screenshots.viewport)
    elif report.screenshots and report.screenshots.full_page:
        ss_uri = _encode_image(report.screenshots.full_page)

    pending_note = None
    if not has_analyst:
        pending_note = (
            "Strategic evaluation lenses (Brand & Messaging, Experience & Design, "
            "Conversion & Strategy) are pending analyst review."
        )

    return {
        "label": label,
        "url": report.normalized_url,
        "type_label": "Primary Site" if is_primary else f"Competitor {index}",
        "screenshot_data_uri": ss_uri,
        "score_ring_svg": score_ring(
            report.retina_score.total,
            max_score,
        ),
        "bar_chart_svg": horizontal_bar_chart(scores),
        "pending_note": pending_note,
    }


def _build_analyst_observations(
    analysis: AnalysisRun,
) -> list[list[dict]]:
    """Build analyst observation pages from all reports with analyst scores."""
    pages: list[list[dict]] = []

    all_reports = [analysis.primary_site] + analysis.competitors
    for report in all_reports:
        if not _has_analyst_scores(report):
            continue

        report_lenses: list[dict] = []
        for ls in report.retina_score.lens_scores:
            if ls.is_automated:
                continue

            lens_name = LENS_NAMES_FULL.get(ls.lens.value, ls.lens.value)

            subdims = []
            from retina.scoring.analyst import LENS_DEFINITIONS
            definitions = LENS_DEFINITIONS.get(ls.lens.value, {})
            for dim_key, dim_max in definitions.items():
                dim_score = ls.breakdown.get(dim_key, 0)
                dim_label = dim_key.replace("_", " ").title()
                subdims.append((dim_label, f"{dim_score:.1f}", f"{dim_max:.0f}"))

            ss_uri = None
            if report.screenshots and report.screenshots.analyst_overrides:
                override_path = report.screenshots.analyst_overrides.get(ls.lens.value)
                if override_path:
                    ss_uri = _encode_image(override_path)

            report_lenses.append({
                "lens_name": f"{lens_name} \u2014 {_site_label(report.normalized_url)}",
                "score": f"{ls.score:.1f}",
                "subdimensions": subdims,
                "observations": ls.notes or "",
                "screenshot_uri": ss_uri,
                "lens_color": LENS_COLORS.get(ls.lens.value, "#0066FF"),
            })

        for i in range(0, len(report_lenses), 3):
            pages.append(report_lenses[i : i + 3])

    return pages


def _build_roadmap_sections(analysis: AnalysisRun) -> list[dict]:
    """Build roadmap grouped by quadrant with colored sections."""
    if not analysis.ai_analysis or not analysis.ai_analysis.recommendations:
        return []

    by_quadrant: dict[str, list] = {}
    for rec in analysis.ai_analysis.recommendations:
        q = rec.quadrant.value
        by_quadrant.setdefault(q, []).append(rec)

    sections = []
    for q_key in QUADRANT_PRIORITY:
        recs = by_quadrant.get(q_key, [])
        if not recs:
            continue
        sections.append({
            "label": QUADRANT_LABELS.get(q_key, q_key),
            "color": ROADMAP_QUADRANT_COLORS.get(q_key, "#9BA8B7"),
            "recs": [
                {
                    "title": r.title,
                    "description": _truncate(r.description, 250),
                    "lens": getattr(r, "related_gaps", [""])[0] if r.related_gaps else "",
                }
                for r in recs
            ],
        })

    return sections


def _build_all_lens_pages(
    analysis: AnalysisRun,
    assets_dir: Path,
    lens_icons: dict[str, str],
    screenshot_uri: str | None = None,
    subdim_observations: dict[str, dict[str, str]] | None = None,
) -> list[dict]:
    """Build data for ALL lens pages (automated + analyst).

    Creates a page for each of the 5 lenses in LENS_ORDER. For analyst lenses,
    sub-dimension definitions come from LENS_DEFINITIONS. For automated lenses,
    sub-dimensions are derived from the breakdown dict with a default max of 5.0.

    Args:
        analysis: The analysis run.
        assets_dir: Path to assets directory.
        lens_icons: Dict of lens_key -> SVG string for icons.
        screenshot_uri: Data URI for the site screenshot.
        subdim_observations: Optional dict of {lens_key: {subdim_key: observation_text}}.

    Returns:
        List of dicts, one per lens page, ordered by LENS_ORDER.
    """
    from retina.scoring.analyst import LENS_DEFINITIONS

    pages: list[dict] = []
    primary = analysis.primary_site
    obs_map = subdim_observations or {}

    # Index lens scores by key for ordered iteration
    ls_by_key: dict[str, object] = {}
    for ls in primary.retina_score.lens_scores:
        ls_by_key[ls.lens.value] = ls

    for lens_key in LENS_ORDER:
        ls = ls_by_key.get(lens_key)
        if ls is None:
            continue

        color = LENS_COLORS.get(lens_key, "#0066FF")
        name = LENS_NAMES_FULL.get(lens_key, lens_key)
        subtitle = LENS_SUBTITLES.get(lens_key, "")

        # Score ring for this lens (score/20)
        ring_svg = score_ring(
            ls.score, 20.0,
            size=100, stroke_width=8,
            color=color, show_max=True,
        )

        # Overall observations from notes
        observations = ls.notes or ""
        observation_paragraphs = [
            p.strip() for p in observations.split("\n\n") if p.strip()
        ] if observations else []

        # Sub-dimensions: use LENS_DEFINITIONS for analyst lenses,
        # fall back to breakdown keys for automated lenses
        definitions = LENS_DEFINITIONS.get(lens_key, {})
        lens_obs = obs_map.get(lens_key, {})
        subdimensions = []

        if definitions:
            # Analyst lens — use formal definitions
            for dim_key, dim_max in definitions.items():
                dim_score = ls.breakdown.get(dim_key, 0.0)
                dim_name = SUBDIM_DISPLAY_NAMES.get(
                    dim_key, dim_key.replace("_", " ").title()
                )
                dim_observation = lens_obs.get(dim_key, "")

                dim_ring_svg = score_ring(
                    dim_score, dim_max,
                    size=56, stroke_width=5,
                    color=color, show_max=True,
                )

                subdimensions.append({
                    "name": dim_name,
                    "score": dim_score,
                    "max_score": dim_max,
                    "ring_svg": dim_ring_svg,
                    "observation": dim_observation,
                })
        else:
            # Automated lens — derive from breakdown dict
            for dim_key, dim_score in ls.breakdown.items():
                dim_max = 5.0  # default max per sub-dimension
                dim_name = SUBDIM_DISPLAY_NAMES.get(
                    dim_key, dim_key.replace("_", " ").title()
                )
                dim_observation = lens_obs.get(dim_key, "")

                dim_ring_svg = score_ring(
                    dim_score, dim_max,
                    size=56, stroke_width=5,
                    color=color, show_max=True,
                )

                subdimensions.append({
                    "name": dim_name,
                    "score": dim_score,
                    "max_score": dim_max,
                    "ring_svg": dim_ring_svg,
                    "observation": dim_observation,
                })

        pages.append({
            "lens_key": lens_key,
            "name": name,
            "color": color,
            "subtitle": subtitle,
            "is_automated": ls.is_automated,
            "icon_svg": lens_icons.get(lens_key, ""),
            "score_ring_svg": ring_svg,
            "screenshot_uri": screenshot_uri,
            "observations": observations,
            "observation_paragraphs": observation_paragraphs,
            "subdimensions": subdimensions,
        })

    return pages


def _build_tech_summary(analysis: AnalysisRun) -> list[tuple[str, str]]:
    """Extract a concise tech stack summary: [(category_label, names_str), ...]."""
    if not analysis.primary_site.tech_stack:
        return []

    by_cat: dict[str, list[str]] = {}
    for tech in analysis.primary_site.tech_stack.technologies:
        override = TECH_NAME_OVERRIDES.get(tech.name)
        if override:
            by_cat.setdefault(override, [])
            if tech.name not in by_cat[override]:
                by_cat[override].append(tech.name)
            continue

        for cat in tech.categories:
            mapped = TECH_CATEGORY_MAP.get(cat)
            if mapped:
                by_cat.setdefault(mapped, [])
                if tech.name not in by_cat[mapped]:
                    by_cat[mapped].append(tech.name)
                break

    result = []
    for cat in ["CMS", "Analytics", "CRM", "Framework"]:
        names = by_cat.get(cat, [])
        if names:
            result.append((cat, ", ".join(names[:5])))

    return result


def _build_tech_stack_full(analysis: AnalysisRun) -> dict[str, list[str]]:
    """Build the full technology stack grouped by category."""
    if not analysis.primary_site.tech_stack:
        return {}

    by_cat: dict[str, list[str]] = {}
    for tech in analysis.primary_site.tech_stack.technologies:
        assigned = False
        override = TECH_NAME_OVERRIDES.get(tech.name)
        if override:
            by_cat.setdefault(override, [])
            if tech.name not in by_cat[override]:
                by_cat[override].append(tech.name)
            assigned = True

        if not assigned:
            for cat in tech.categories:
                mapped = TECH_CATEGORY_MAP.get(cat)
                if mapped:
                    by_cat.setdefault(mapped, [])
                    if tech.name not in by_cat[mapped]:
                        by_cat[mapped].append(tech.name)
                    assigned = True
                    break

        if not assigned and tech.categories:
            cat_name = tech.categories[0]
            by_cat.setdefault(cat_name, [])
            if tech.name not in by_cat[cat_name]:
                by_cat[cat_name].append(tech.name)

    return by_cat


# ---------------------------------------------------------------------------
# Jinja2 custom filters
# ---------------------------------------------------------------------------


def _safe_svg_white(svg_str: str) -> str:
    """Convert dark SVG fills to white for dark backgrounds."""
    if not svg_str:
        return ""
    return (
        svg_str
        .replace('fill="#000227"', 'fill="#FFFFFF"')
        .replace('fill="#0A0E27"', 'fill="#FFFFFF"')
        .replace('fill="#1A1A2E"', 'fill="#FFFFFF"')
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render_pdf(
    analysis: AnalysisRun,
    output_path: str | Path,
    *,
    assets_dir: str | Path = "assets",
    interpretations: dict[str, dict] | None = None,
    analyst_name: str | None = None,
    project_title: str | None = None,
    subdim_observations: dict[str, dict[str, str]] | None = None,
    screenshot_data_uri: str | None = None,
) -> Path:
    """Render a complete PDF report from an AnalysisRun.

    Args:
        analysis: The completed analysis run with all data.
        output_path: Where to save the PDF.
        assets_dir: Path to the assets directory for logos.
        interpretations: Optional dict mapping site URLs to interpretation dicts.
        analyst_name: Name of the analyst for the summary page.
        project_title: Display name for the project (falls back to site label).
        subdim_observations: Per-lens per-subdim observation text.
        screenshot_data_uri: Pre-encoded screenshot data URI. When provided,
            takes priority over ScreenshotData file paths. Pass None to omit
            the screenshot entirely.

    Returns:
        Path to the generated PDF.
    """
    # Guarantee native libs are discoverable in this thread/process
    _ensure_weasyprint_libs()

    from weasyprint import HTML

    output_path = Path(output_path)
    assets_dir = Path(assets_dir)

    # Load logos and icons
    retina_logo = _read_svg(assets_dir / "Matic-Retina.svg")
    matic_logo = _read_svg(assets_dir / "Matic-Logo.svg")

    lens_icons = {}
    icon_files = {
        "performance_technical_health": "performance_icon.svg",
        "seo_ai_visibility": "seo_icon.svg",
        "brand_messaging": "brand_icon.svg",
        "experience_design": "experience_icon.svg",
        "conversion_strategy": "conversion_icon.svg",
    }
    for lens_key, filename in icon_files.items():
        lens_icons[lens_key] = _read_svg(assets_dir / filename) or ""

    # Primary site info
    primary = analysis.primary_site
    competitors = analysis.competitors

    # Project title
    title = project_title or _site_label(primary.normalized_url)

    # Executive summary
    exec_summary = ""
    exec_paragraphs = []
    if analysis.ai_analysis and analysis.ai_analysis.executive_summary:
        exec_summary = analysis.ai_analysis.executive_summary
        exec_paragraphs = [p.strip() for p in exec_summary.split("\n\n") if p.strip()]

    # Lens scores for charts
    lens_scores = _get_lens_scores(primary)
    lens_scores_float = {k: (v or 0) for k, v in lens_scores.items()}
    max_score = _get_max_score(primary)

    # Segmented donut chart
    donut_svg = segmented_donut(lens_scores_float, primary.retina_score.total)

    # Summary bar chart
    summary_bar_svg = horizontal_bar_chart(lens_scores)

    # Screenshot: prefer explicit data URI > viewport path > full-page path
    primary_ss_uri = screenshot_data_uri
    if not primary_ss_uri and primary.screenshots and primary.screenshots.viewport:
        primary_ss_uri = _encode_image(primary.screenshots.viewport)
    if not primary_ss_uri and primary.screenshots and primary.screenshots.full_page:
        primary_ss_uri = _encode_image(primary.screenshots.full_page)

    # Tech stack summary
    tech_summary = _build_tech_summary(analysis)

    # Recommendations
    has_recs = bool(
        analysis.ai_analysis
        and analysis.ai_analysis.recommendations
    )

    recommendation_quadrants = []
    if has_recs:
        quad_config = [
            ("no_brainer", "No-Brainers", "Low effort, high impact", Q_NO_BRAINER),
            ("growth_move", "Growth Moves", "High effort, high impact", Q_GROWTH),
            ("quick_win", "Quick Wins", "Low effort, lower impact", Q_QUICK_WIN),
            ("transformational", "Transformational", "High effort, long-term payoff", Q_TRANSFORM),
        ]
        by_q: dict[str, list] = {}
        for rec in analysis.ai_analysis.recommendations:
            by_q.setdefault(rec.quadrant.value, []).append(rec)

        for q_key, label, desc, color in quad_config:
            recs = by_q.get(q_key, [])
            recommendation_quadrants.append({
                "label": label,
                "descriptor": desc,
                "color": color,
                "recs": [
                    {
                        "title": r.title,
                        "description": r.description or "",
                        "lens_color": LENS_COLORS.get(
                            r.related_gaps[0], None
                        ) if r.related_gaps else None,
                        "lens_name": LENS_BADGE_NAMES.get(
                            r.related_gaps[0], ""
                        ) if r.related_gaps else "",
                    }
                    for r in recs
                ],
            })

    # All lens pages (automated + analyst)
    analyst_lens_pages = _build_all_lens_pages(
        analysis,
        assets_dir,
        lens_icons,
        screenshot_uri=primary_ss_uri,
        subdim_observations=subdim_observations,
    )

    # Build template context
    context = {
        "retina_logo_svg": retina_logo,
        "matic_logo_svg": matic_logo,
        "lens_icons": lens_icons,
        "primary_url": primary.normalized_url,
        "project_title": title,
        "analysis_date": analysis.created_at.strftime("%m.%d.%Y"),
        "analyst_name": analyst_name,
        "donut_chart_svg": donut_svg,
        "summary_bar_chart_svg": summary_bar_svg,
        "screenshot_data_uri": primary_ss_uri,
        "tech_summary": tech_summary,
        "executive_summary": exec_summary,
        "executive_summary_paragraphs": exec_paragraphs,
        "lens_descriptions": LENS_DESCRIPTIONS,
        "lens_names": LENS_NAMES_FULL,
        "lens_order": LENS_ORDER,
        "analyst_lens_pages": analyst_lens_pages,
        "has_recommendations": has_recs,
        "recommendation_quadrants": recommendation_quadrants,
        "quadrant_labels": QUADRANT_LABELS,
        "quadrant_colors": QUADRANT_COLORS,
    }

    # Render HTML
    env = Environment(loader=BaseLoader(), autoescape=False)
    env.filters["safe_svg_white"] = _safe_svg_white
    template = env.from_string(REPORT_TEMPLATE)
    html_content = template.render(**context)

    # Convert to PDF
    logger.info("Generating PDF report: %s", output_path)
    html_doc = HTML(string=html_content)
    html_doc.write_pdf(str(output_path))

    logger.info("PDF report saved: %s (%d bytes)", output_path, output_path.stat().st_size)
    return output_path
