"""PDF report renderer for Retina analysis runs.

Assembles an AnalysisRun into a branded HTML document, then converts
to PDF via WeasyPrint. Uses Jinja2 for template rendering and inline
SVG charts generated by the charts module.
"""

from __future__ import annotations

import base64
import logging
import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, BaseLoader


def _ensure_weasyprint_libs() -> None:
    """Ensure Homebrew dynamic libraries are discoverable on macOS.

    WeasyPrint depends on GLib/Pango/Cairo which are installed via Homebrew
    but may not be on the default library search path.
    """
    if os.environ.get("DYLD_LIBRARY_PATH"):
        return  # Already set

    # Check common Homebrew lib paths
    brew_lib = Path("/opt/homebrew/lib")
    if not brew_lib.exists():
        brew_lib = Path("/usr/local/lib")
    if brew_lib.exists() and (brew_lib / "libgobject-2.0.dylib").exists():
        os.environ["DYLD_LIBRARY_PATH"] = str(brew_lib)


_ensure_weasyprint_libs()

from retina.models.normalized import AnalysisRun, SiteReport, StrategicQuadrant
from retina.report.charts import (
    LENS_ORDER,
    LENS_LABELS_SHORT,
    QUADRANT_COLORS,
    grouped_bar_chart,
    horizontal_bar_chart,
    quadrant_matrix,
    score_ring,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

LENS_DESCRIPTIONS = {
    "performance_technical_health": (
        "How fast, stable, and well-built the website is under the hood "
        "\u2014 page speed, code quality, security, and core web vitals."
    ),
    "seo_ai_visibility": (
        "How discoverable the website is to search engines, AI assistants, "
        "and the algorithms that increasingly determine who gets found first."
    ),
    "brand_messaging": (
        "How clearly the website communicates who it is for, what it offers, "
        "and why it matters."
    ),
    "experience_design": (
        "How intuitive, modern, and intentional the website feels \u2014 from "
        "navigation and layout to visual hierarchy and mobile responsiveness."
    ),
    "conversion_strategy": (
        "How effectively the website turns attention into action through clear "
        "CTAs, logical user paths, and trust-building content."
    ),
}

QUADRANT_LABELS = {
    "no_brainer": "No-Brainers",
    "growth_move": "Growth Moves",
    "quick_win": "Quick Wins",
    "transformational": "Transformational",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _encode_image(path: str | Path) -> str | None:
    """Read an image file and return a data URI, or None if missing."""
    p = Path(path)
    if not p.exists():
        logger.warning("Image not found: %s", p)
        return None
    suffix = p.suffix.lower()
    mime = {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".svg": "image/svg+xml",
        ".webp": "image/webp",
    }.get(suffix, "image/png")
    data = p.read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:{mime};base64,{b64}"


def _read_svg(path: str | Path) -> str | None:
    """Read an SVG file and return its content, or None if missing."""
    p = Path(path)
    if not p.exists():
        return None
    return p.read_text(encoding="utf-8")


def _get_lens_scores(report: SiteReport) -> dict[str, float | None]:
    """Extract a dict of lens_key -> score from a SiteReport."""
    scores: dict[str, float | None] = {}
    scored_keys = set()
    for ls in report.retina_score.lens_scores:
        scores[ls.lens.value] = ls.score
        scored_keys.add(ls.lens.value)
    # Fill missing lenses with None
    for key in LENS_ORDER:
        if key not in scored_keys:
            scores[key] = None
    return scores


def _has_analyst_scores(report: SiteReport) -> bool:
    """Check if a report has any analyst-scored lenses."""
    return any(not ls.is_automated for ls in report.retina_score.lens_scores)


def _get_max_score(report: SiteReport) -> float:
    """Determine max possible score based on which lenses are present."""
    return 100.0 if _has_analyst_scores(report) else 40.0


def _truncate(text: str, max_len: int = 200) -> str:
    """Truncate text to max_len, adding ellipsis if needed."""
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."


def _site_label(url: str) -> str:
    """Extract a readable label from a URL."""
    from urllib.parse import urlparse
    parsed = urlparse(url)
    return parsed.netloc or url


# ---------------------------------------------------------------------------
# Template
# ---------------------------------------------------------------------------


REPORT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
/* Inter font — falls back to system sans-serif for PDF reliability */

@page {
    size: Letter;
    margin: 0;
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

html, body {
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    font-size: 11px;
    line-height: 1.5;
    color: #000227;
    -webkit-font-smoothing: antialiased;
}

.page {
    width: 8.5in;
    min-height: 11in;
    padding: 0.75in 0.85in;
    page-break-after: always;
    position: relative;
}

.page:last-child {
    page-break-after: avoid;
}

/* ---- Cover ---- */
.cover {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: flex-start;
    background: #000227;
    color: #FFFFFF;
    padding: 1.2in 1in;
}

.cover-logo {
    margin-bottom: 0.6in;
}

.cover-logo svg {
    height: 48px;
    width: auto;
}

.cover-title {
    font-size: 36px;
    font-weight: 300;
    letter-spacing: -0.5px;
    line-height: 1.15;
    margin-bottom: 0.15in;
    color: #FFFFFF;
}

.cover-accent {
    color: #076EFF;
}

.cover-divider {
    width: 60px;
    height: 3px;
    background: #076EFF;
    margin: 0.35in 0;
    border: none;
}

.cover-url {
    font-size: 18px;
    font-weight: 400;
    color: rgba(255,255,255,0.85);
    margin-bottom: 0.15in;
}

.cover-meta {
    font-size: 13px;
    font-weight: 300;
    color: rgba(255,255,255,0.55);
    margin-top: 0.4in;
}

.cover-meta span {
    display: block;
    margin-bottom: 4px;
}

/* ---- Section headers ---- */
.section-header {
    font-size: 22px;
    font-weight: 600;
    letter-spacing: -0.3px;
    margin-bottom: 0.3in;
    padding-bottom: 8px;
    border-bottom: 2px solid #076EFF;
    color: #000227;
}

.section-subtitle {
    font-size: 13px;
    font-weight: 400;
    color: #5A6778;
    margin-bottom: 0.25in;
    line-height: 1.6;
}

/* ---- Body text ---- */
.body-text {
    font-size: 11px;
    font-weight: 400;
    line-height: 1.7;
    color: #2A3444;
    margin-bottom: 14px;
}

.body-text-lg {
    font-size: 12px;
    line-height: 1.7;
    color: #2A3444;
    margin-bottom: 16px;
}

/* ---- Scoring Overview ---- */
.lens-grid {
    display: flex;
    flex-wrap: wrap;
    gap: 16px;
    margin-bottom: 0.2in;
}

.lens-card {
    width: calc(50% - 8px);
    padding: 14px 16px;
    border: 1px solid #E8EDF3;
    border-radius: 6px;
    background: #FAFBFC;
}

.lens-card-title {
    font-size: 12px;
    font-weight: 600;
    color: #000227;
    margin-bottom: 6px;
}

.lens-card-desc {
    font-size: 10px;
    font-weight: 400;
    color: #5A6778;
    line-height: 1.55;
}

.lens-note {
    font-size: 10px;
    color: #5A6778;
    font-style: italic;
    margin-top: 0.15in;
    padding: 10px 14px;
    background: #F4F6F9;
    border-radius: 4px;
}

/* ---- Scorecard ---- */
.scorecard-header {
    display: flex;
    align-items: center;
    gap: 0.3in;
    margin-bottom: 0.25in;
}

.scorecard-label {
    font-size: 10px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 1.5px;
    color: #076EFF;
    margin-bottom: 4px;
}

.scorecard-url {
    font-size: 16px;
    font-weight: 600;
    color: #000227;
    margin-bottom: 2px;
}

.scorecard-body {
    display: flex;
    gap: 0.3in;
    align-items: flex-start;
}

.scorecard-screenshot {
    width: 260px;
    flex-shrink: 0;
    border: 1px solid #E8EDF3;
    border-radius: 6px;
    overflow: hidden;
}

.scorecard-screenshot img {
    width: 100%;
    height: auto;
    display: block;
}

.scorecard-chart {
    flex: 1;
}

/* ---- Comparison ---- */
.comparison-chart {
    margin-top: 0.2in;
}

/* ---- Analyst Observations ---- */
.analyst-section {
    margin-bottom: 0.35in;
}

.analyst-lens-title {
    font-size: 16px;
    font-weight: 600;
    color: #000227;
    margin-bottom: 4px;
}

.analyst-lens-score {
    font-size: 13px;
    font-weight: 500;
    color: #076EFF;
    margin-bottom: 12px;
}

.subdim-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 14px;
}

.subdim-table th,
.subdim-table td {
    padding: 6px 10px;
    text-align: left;
    font-size: 10px;
    border-bottom: 1px solid #E8EDF3;
}

.subdim-table th {
    font-weight: 600;
    color: #5A6778;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    font-size: 9px;
}

.subdim-table td:last-child {
    text-align: right;
    font-weight: 600;
    color: #000227;
}

.observations-text {
    font-size: 11px;
    line-height: 1.65;
    color: #2A3444;
    padding: 12px 16px;
    background: #FAFBFC;
    border-radius: 4px;
    border-left: 3px solid #076EFF;
    margin-bottom: 10px;
}

.analyst-screenshot-thumb {
    max-width: 200px;
    border: 1px solid #E8EDF3;
    border-radius: 4px;
    margin-top: 8px;
}

/* ---- Quadrant ---- */
.quadrant-legend {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
    margin-bottom: 0.15in;
}

.quadrant-legend-item {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 10px;
    font-weight: 500;
}

.quadrant-dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    display: inline-block;
}

.quadrant-chart {
    margin-bottom: 0.2in;
}

/* ---- Roadmap ---- */
.roadmap-item {
    display: flex;
    align-items: flex-start;
    gap: 12px;
    padding: 10px 0;
    border-bottom: 1px solid #E8EDF3;
}

.roadmap-num {
    width: 26px;
    height: 26px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 11px;
    font-weight: 700;
    color: #FFFFFF;
    flex-shrink: 0;
}

.roadmap-content {
    flex: 1;
}

.roadmap-title {
    font-size: 12px;
    font-weight: 600;
    color: #000227;
    margin-bottom: 2px;
}

.roadmap-desc {
    font-size: 10px;
    color: #5A6778;
    line-height: 1.5;
}

.roadmap-meta {
    display: flex;
    gap: 12px;
    margin-top: 4px;
}

.roadmap-tag {
    font-size: 9px;
    font-weight: 500;
    padding: 2px 8px;
    border-radius: 3px;
    background: #F0F3F7;
    color: #5A6778;
}

/* ---- Methodology ---- */
.methodology {
    padding-top: 0.3in;
}

.methodology p {
    font-size: 10px;
    line-height: 1.65;
    color: #5A6778;
    margin-bottom: 10px;
}

.methodology .source-label {
    font-weight: 600;
    color: #000227;
}

.footer-logo {
    margin-top: 0.4in;
    opacity: 0.5;
}

.footer-logo svg {
    height: 28px;
}

</style>
</head>
<body>

<!-- ============================================================ -->
<!-- COVER PAGE                                                     -->
<!-- ============================================================ -->
<div class="page cover">
    {% if retina_logo_svg %}
    <div class="cover-logo">{{ retina_logo_svg | replace('fill="#000227"', 'fill="#FFFFFF"') }}</div>
    {% else %}
    <div class="cover-logo" style="font-size: 28px; font-weight: 600; letter-spacing: -0.5px;">RETINA</div>
    {% endif %}

    <h1 class="cover-title">Website Intelligence<br><span class="cover-accent">Report</span></h1>
    <hr class="cover-divider">
    <div class="cover-url">{{ primary_url }}</div>

    {% if competitor_urls %}
    <div style="font-size: 12px; color: rgba(255,255,255,0.5); margin-top: 4px;">
        vs {{ competitor_urls | join(', ') }}
    </div>
    {% endif %}

    <div class="cover-meta">
        <span>{{ analysis_date }}</span>
        <span>Prepared by Matic Digital</span>
    </div>
</div>

<!-- ============================================================ -->
<!-- EXECUTIVE SUMMARY                                              -->
<!-- ============================================================ -->
<div class="page">
    <h2 class="section-header">Executive Summary</h2>

    {% if executive_summary %}
        {% for paragraph in executive_summary_paragraphs %}
        <p class="body-text-lg">{{ paragraph }}</p>
        {% endfor %}
    {% else %}
    <p class="body-text-lg" style="color: #9BA8B7; font-style: italic;">
        Executive summary not available. Run with competitor URLs and an Anthropic API key
        to generate AI-powered competitive analysis.
    </p>
    {% endif %}
</div>

<!-- ============================================================ -->
<!-- SCORING OVERVIEW                                               -->
<!-- ============================================================ -->
<div class="page">
    <h2 class="section-header">The Retina Scoring Framework</h2>
    <p class="section-subtitle">
        Five lenses assess digital experience readiness across complementary dimensions
        of website performance and strategic effectiveness.
    </p>

    <div class="lens-grid">
    {% for lens_key, lens_desc in lens_descriptions.items() %}
        <div class="lens-card">
            <div class="lens-card-title">{{ lens_names[lens_key] }}</div>
            <div class="lens-card-desc">{{ lens_desc }}</div>
        </div>
    {% endfor %}
    </div>

    <div class="lens-note">
        Each lens is worth 20 points. The composite 100-point Retina Score measures
        overall digital experience readiness relative to the competitive set.
    </div>
</div>

<!-- ============================================================ -->
<!-- SITE SCORECARDS                                                -->
<!-- ============================================================ -->
{% for sc in scorecards %}
<div class="page">
    <h2 class="section-header">{{ sc.label }}</h2>

    <div class="scorecard-header">
        <div>
            <div class="scorecard-label">{{ sc.type_label }}</div>
            <div class="scorecard-url">{{ sc.url }}</div>
        </div>
    </div>

    <div class="scorecard-body">
        {% if sc.screenshot_data_uri %}
        <div class="scorecard-screenshot">
            <img src="{{ sc.screenshot_data_uri }}" alt="Screenshot of {{ sc.url }}" />
        </div>
        {% endif %}

        <div class="scorecard-chart">
            <div style="text-align: center; margin-bottom: 12px;">
                {{ sc.score_ring_svg }}
            </div>
            {{ sc.bar_chart_svg }}
        </div>
    </div>

    {% if sc.pending_note %}
    <div class="lens-note" style="margin-top: 14px;">
        {{ sc.pending_note }}
    </div>
    {% endif %}
</div>
{% endfor %}

<!-- ============================================================ -->
<!-- COMPETITIVE COMPARISON                                         -->
<!-- ============================================================ -->
{% if comparison_chart_svg %}
<div class="page">
    <h2 class="section-header">Competitive Comparison</h2>
    <p class="section-subtitle">
        All sites compared across the five Retina lenses. Gaps and advantages
        are immediately visible in the relative bar lengths.
    </p>

    <div class="comparison-chart">
        {{ comparison_chart_svg }}
    </div>
</div>
{% endif %}

<!-- ============================================================ -->
<!-- ANALYST OBSERVATIONS                                           -->
<!-- ============================================================ -->
{% for obs_page in analyst_pages %}
<div class="page">
    <h2 class="section-header">Analyst Observations</h2>

    {% for obs in obs_page %}
    <div class="analyst-section">
        <div class="analyst-lens-title">{{ obs.lens_name }}</div>
        <div class="analyst-lens-score">{{ obs.score }} / 20</div>

        {% if obs.subdimensions %}
        <table class="subdim-table">
            <thead>
                <tr>
                    <th>Sub-Dimension</th>
                    <th>Score</th>
                </tr>
            </thead>
            <tbody>
            {% for dim_name, dim_score, dim_max in obs.subdimensions %}
                <tr>
                    <td>{{ dim_name }}</td>
                    <td>{{ dim_score }} / {{ dim_max }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endif %}

        {% if obs.observations %}
        <div class="observations-text">{{ obs.observations }}</div>
        {% endif %}

        {% if obs.screenshot_uri %}
        <img class="analyst-screenshot-thumb" src="{{ obs.screenshot_uri }}" alt="Analyst screenshot" />
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endfor %}

<!-- ============================================================ -->
<!-- STRATEGIC QUADRANT                                             -->
<!-- ============================================================ -->
{% if has_recommendations %}
<div class="page">
    <h2 class="section-header">Strategic Quadrant</h2>
    <p class="section-subtitle">
        AI-generated recommendations plotted by effort and impact.
        Numbers correspond to the prioritized roadmap on the following page.
    </p>

    <div class="quadrant-chart">
        {{ quadrant_svg }}
    </div>

    <div class="quadrant-legend">
        {% for q_key, q_label in quadrant_labels.items() %}
        <div class="quadrant-legend-item">
            <span class="quadrant-dot" style="background: {{ quadrant_colors[q_key] }};"></span>
            {{ q_label }}
        </div>
        {% endfor %}
    </div>
</div>

<!-- ============================================================ -->
<!-- PRIORITIZED ROADMAP                                            -->
<!-- ============================================================ -->
<div class="page">
    <h2 class="section-header">Prioritized Roadmap</h2>
    <p class="section-subtitle">
        Recommendations listed in suggested execution sequence, starting
        with highest-impact, lowest-effort items.
    </p>

    {% for rec in roadmap_items %}
    <div class="roadmap-item">
        <div class="roadmap-num" style="background: {{ rec.color }};">{{ rec.num }}</div>
        <div class="roadmap-content">
            <div class="roadmap-title">{{ rec.title }}</div>
            <div class="roadmap-desc">{{ rec.description }}</div>
            <div class="roadmap-meta">
                <span class="roadmap-tag">{{ rec.quadrant_label }}</span>
                <span class="roadmap-tag">Effort: {{ rec.effort }}</span>
                <span class="roadmap-tag">Impact: {{ rec.impact }}</span>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}

<!-- ============================================================ -->
<!-- METHODOLOGY                                                    -->
<!-- ============================================================ -->
<div class="page">
    <h2 class="section-header">Methodology</h2>

    <div class="methodology">
        <p>
            <span class="source-label">Automated Scoring</span> is powered by
            Google Lighthouse via the PageSpeed Insights API. Each URL is analyzed
            for both mobile and desktop, producing scores for Performance,
            Accessibility, Best Practices, and SEO, plus Core Web Vitals metrics
            (LCP, FCP, CLS, TBT, INP, Speed Index).
        </p>
        <p>
            <span class="source-label">Technology Detection</span> is performed via
            the BuiltWith API, identifying frameworks, CDNs, analytics tools, and
            other technologies in use.
        </p>
        <p>
            <span class="source-label">Strategic Evaluation</span> (Brand &amp; Messaging,
            Experience &amp; Design, Conversion &amp; Strategy) is conducted by
            Matic Digital analysts using a structured rubric with documented
            sub-dimensions and observations.
        </p>
        <p>
            <span class="source-label">AI-Assisted Analysis</span> is powered by
            Anthropic's Claude. The model synthesizes automated data and analyst
            scores to produce competitive comparisons, gap identification, and
            prioritized strategic recommendations.
        </p>
        <p style="margin-top: 18px;">
            <span class="source-label">Scoring Scale:</span>
            Each of the five lenses is scored 0\u201320 points. The composite Retina
            Score (0\u2013100) represents overall digital experience readiness.
            Automated lenses (Performance &amp; Technical Health, SEO &amp; AI Visibility)
            contribute up to 40 points. Analyst-scored lenses (Brand &amp; Messaging,
            Experience &amp; Design, Conversion &amp; Strategy) contribute up to 60 points
            when a rubric is provided.
        </p>
    </div>

    {% if matic_logo_svg %}
    <div class="footer-logo">{{ matic_logo_svg }}</div>
    {% endif %}
</div>

</body>
</html>
"""


# ---------------------------------------------------------------------------
# Data preparation
# ---------------------------------------------------------------------------

# Priority order for roadmap: no-brainers first, then quick wins, growth, transformational
QUADRANT_PRIORITY = ["no_brainer", "quick_win", "growth_move", "transformational"]

LENS_NAMES_FULL = {
    "performance_technical_health": "Performance & Technical Health",
    "seo_ai_visibility": "SEO & AI Visibility",
    "brand_messaging": "Brand & Messaging",
    "experience_design": "Experience & Design",
    "conversion_strategy": "Conversion & Strategy",
}


def _build_scorecard(
    report: SiteReport,
    *,
    is_primary: bool,
    index: int,
) -> dict:
    """Build template context for a single site scorecard."""
    scores = _get_lens_scores(report)
    max_score = _get_max_score(report)
    has_analyst = _has_analyst_scores(report)
    label = _site_label(report.normalized_url)

    # Screenshot
    ss_uri = None
    if report.screenshots and report.screenshots.viewport:
        ss_uri = _encode_image(report.screenshots.viewport)
    elif report.screenshots and report.screenshots.full_page:
        ss_uri = _encode_image(report.screenshots.full_page)

    # Pending note
    pending_note = None
    if not has_analyst:
        pending_note = (
            "Analyst lenses (Brand & Messaging, Experience & Design, "
            "Conversion & Strategy) are pending strategic evaluation. "
            "Score shown reflects automated lenses only."
        )

    return {
        "label": label,
        "url": report.normalized_url,
        "type_label": "Primary Site" if is_primary else f"Competitor {index}",
        "screenshot_data_uri": ss_uri,
        "score_ring_svg": score_ring(
            report.retina_score.total,
            max_score,
        ),
        "bar_chart_svg": horizontal_bar_chart(scores),
        "pending_note": pending_note,
    }


def _build_analyst_observations(
    analysis: AnalysisRun,
) -> list[list[dict]]:
    """Build analyst observation pages from all reports with analyst scores.

    Returns a list of pages, each page being a list of lens observations.
    Groups up to 3 lenses per page.
    """
    pages: list[list[dict]] = []

    all_reports = [analysis.primary_site] + analysis.competitors
    for report in all_reports:
        if not _has_analyst_scores(report):
            continue

        report_lenses: list[dict] = []
        for ls in report.retina_score.lens_scores:
            if ls.is_automated:
                continue

            lens_name = LENS_NAMES_FULL.get(ls.lens.value, ls.lens.value)

            # Sub-dimensions from breakdown
            subdims = []
            from retina.scoring.analyst import LENS_DEFINITIONS
            definitions = LENS_DEFINITIONS.get(ls.lens.value, {})
            for dim_key, dim_max in definitions.items():
                dim_score = ls.breakdown.get(dim_key, 0)
                dim_label = dim_key.replace("_", " ").title()
                subdims.append((dim_label, f"{dim_score:.1f}", f"{dim_max:.0f}"))

            # Screenshot from analyst overrides
            ss_uri = None
            if report.screenshots and report.screenshots.analyst_overrides:
                override_path = report.screenshots.analyst_overrides.get(ls.lens.value)
                if override_path:
                    ss_uri = _encode_image(override_path)

            report_lenses.append({
                "lens_name": f"{lens_name} \u2014 {_site_label(report.normalized_url)}",
                "score": f"{ls.score:.1f}",
                "subdimensions": subdims,
                "observations": ls.notes or "",
                "screenshot_uri": ss_uri,
            })

        # Group into pages (up to 3 lenses per page)
        for i in range(0, len(report_lenses), 3):
            pages.append(report_lenses[i : i + 3])

    return pages


def _build_roadmap(analysis: AnalysisRun) -> list[dict]:
    """Build the prioritized roadmap from AI recommendations."""
    if not analysis.ai_analysis or not analysis.ai_analysis.recommendations:
        return []

    recs = list(analysis.ai_analysis.recommendations)

    # Sort by quadrant priority, then by impact (high first)
    def sort_key(r):
        q_idx = QUADRANT_PRIORITY.index(r.quadrant.value) if r.quadrant.value in QUADRANT_PRIORITY else 99
        impact_idx = 0 if r.impact.value == "high" else 1
        return (q_idx, impact_idx)

    recs.sort(key=sort_key)

    items = []
    for idx, rec in enumerate(recs):
        q_val = rec.quadrant.value
        items.append({
            "num": idx + 1,
            "title": rec.title,
            "description": _truncate(rec.description, 200),
            "quadrant_label": QUADRANT_LABELS.get(q_val, q_val),
            "effort": rec.effort.value.title(),
            "impact": rec.impact.value.title(),
            "color": QUADRANT_COLORS.get(q_val, "#9BA8B7"),
        })

    return items


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render_pdf(
    analysis: AnalysisRun,
    output_path: str | Path,
    *,
    assets_dir: str | Path = "assets",
) -> Path:
    """Render a complete PDF report from an AnalysisRun.

    Args:
        analysis: The completed analysis run with all data.
        output_path: Where to save the PDF.
        assets_dir: Path to the assets directory for logos.

    Returns:
        Path to the generated PDF.
    """
    from weasyprint import HTML

    output_path = Path(output_path)
    assets_dir = Path(assets_dir)

    # Load logos
    retina_logo = _read_svg(assets_dir / "Matic-Retina.svg")
    matic_logo = _read_svg(assets_dir / "Matic-Logo.svg")

    # Primary site info
    primary = analysis.primary_site
    competitors = analysis.competitors

    # Executive summary
    exec_summary = ""
    exec_paragraphs = []
    if analysis.ai_analysis and analysis.ai_analysis.executive_summary:
        exec_summary = analysis.ai_analysis.executive_summary
        exec_paragraphs = [p.strip() for p in exec_summary.split("\n\n") if p.strip()]

    # Scorecards
    scorecards = [_build_scorecard(primary, is_primary=True, index=0)]
    for idx, comp in enumerate(competitors):
        scorecards.append(_build_scorecard(comp, is_primary=False, index=idx + 1))

    # Comparison chart
    comparison_svg = None
    if competitors:
        all_reports = [primary] + competitors
        site_scores = []
        for r in all_reports:
            label = _site_label(r.normalized_url)
            scores = _get_lens_scores(r)
            site_scores.append((label, scores))
        comparison_svg = grouped_bar_chart(site_scores)

    # Analyst observations
    analyst_pages = _build_analyst_observations(analysis)

    # Quadrant and roadmap
    has_recs = bool(
        analysis.ai_analysis
        and analysis.ai_analysis.recommendations
    )
    quadrant_svg = ""
    roadmap_items = []
    if has_recs:
        rec_dicts = [
            {
                "title": r.title,
                "quadrant": r.quadrant.value,
                "effort": r.effort.value,
                "impact": r.impact.value,
            }
            for r in analysis.ai_analysis.recommendations
        ]
        quadrant_svg = quadrant_matrix(rec_dicts)
        roadmap_items = _build_roadmap(analysis)

    # Lens descriptions for overview page
    lens_names = {
        "performance_technical_health": "Performance & Technical Health",
        "seo_ai_visibility": "SEO & AI Visibility",
        "brand_messaging": "Brand & Messaging",
        "experience_design": "Experience & Design",
        "conversion_strategy": "Conversion & Strategy",
    }

    # Build template context
    context = {
        "retina_logo_svg": retina_logo,
        "matic_logo_svg": matic_logo,
        "primary_url": primary.normalized_url,
        "competitor_urls": [c.normalized_url for c in competitors],
        "analysis_date": analysis.created_at.strftime("%B %d, %Y"),
        "executive_summary": exec_summary,
        "executive_summary_paragraphs": exec_paragraphs,
        "lens_descriptions": LENS_DESCRIPTIONS,
        "lens_names": lens_names,
        "scorecards": scorecards,
        "comparison_chart_svg": comparison_svg,
        "analyst_pages": analyst_pages,
        "has_recommendations": has_recs,
        "quadrant_svg": quadrant_svg,
        "quadrant_labels": QUADRANT_LABELS,
        "quadrant_colors": QUADRANT_COLORS,
        "roadmap_items": roadmap_items,
    }

    # Render HTML
    env = Environment(loader=BaseLoader(), autoescape=False)
    template = env.from_string(REPORT_TEMPLATE)
    html_content = template.render(**context)

    # Convert to PDF
    logger.info("Generating PDF report: %s", output_path)
    html_doc = HTML(string=html_content)
    html_doc.write_pdf(str(output_path))

    logger.info("PDF report saved: %s (%d bytes)", output_path, output_path.stat().st_size)
    return output_path
