[theme]
base = "light"
primaryColor = "#076EFF"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0A0A2E"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
